# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0008_auto_20200402_2149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0024_auto_20200429_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['start_date', 'campaign_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.SmallIntegerField(unique=True)),
                ('type', models.CharField(default='', max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id', 'type'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.CampaignType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='round.Round'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
