# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20200429_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignType',
        ),
    ]
