# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-11 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_delete_campaigntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('LE', 'Leafleting'), ('CA', 'Canvassing'), ('SU', 'Surveying')], default='LE', max_length=20),
        ),
    ]
