# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-11 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20200511_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='round',
        ),
    ]
