# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-11 19:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaign_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('LEAFLET', 'Leafleting'), ('CANVASS', 'Canvassing'), ('SURVEY', 'Surveying')], default='LE', max_length=20),
        ),
    ]
