# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-11 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20200511_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['pk', 'active_date', 'campaign_type', 'name']},
        ),
    ]
