# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0010_auto_20200512_1037'),
        ('campaign', '0010_auto_20200512_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rounds',
            field=models.ManyToManyField(to='round.Round'),
        ),
    ]
