# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-13 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20200512_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='updated_by',
        ),
    ]
