# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-16 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_remove_campaign_updated_by'),
    ]

    operations = [
    ]
