# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-16 14:41
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_remove_campaign_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rounds',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='round', chained_model_field='round', horizontal=True, to='round.Round'),
        ),
    ]
