# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_campaign_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
