# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_auto_20200517_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rounds',
            field=models.ManyToManyField(to='round.Round'),
        ),
    ]
