# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_campaign_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
