# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0023_auto_20200522_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['name', 'active_date', 'campaign_type']},
        ),
    ]
