# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20200522_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='round.Round'),
        ),
    ]
