# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name=300)),
                ('logo_text', models.CharField(max_length=15)),
                ('glyphicon_name', models.CharField(max_length=20)),
                ('image_path', models.TextField(verbose_name=1024)),
                ('image', models.ImageField(upload_to='images')),
                ('address_1', models.CharField(max_length=30)),
                ('address_2', models.CharField(max_length=30)),
                ('address_3', models.CharField(max_length=30)),
                ('address_4', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=8)),
                ('email_address', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
