# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image_path',
            field=models.TextField(),
        ),
    ]
