# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20200226_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='password',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_2',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_3',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_4',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
    ]
