# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20200226_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='glyphicon_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo_text',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
