# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200226_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image_caption',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
