# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_organisation_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='image_caption',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
