# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20200301_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
