# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_organisation_is_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-is_parent']},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Is parent organisation?'),
        ),
    ]
