# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20200308_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_parent', models.BooleanField(default=False, verbose_name='Is parent organisation?')),
                ('logo_text', models.CharField(blank=True, max_length=15)),
                ('glyphicon_name', models.CharField(blank=True, max_length=20)),
                ('image_path', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_caption', models.CharField(blank=True, max_length=70)),
                ('address_1', models.CharField(max_length=40)),
                ('address_2', models.CharField(max_length=40)),
                ('address_3', models.CharField(blank=True, max_length=40)),
                ('address_4', models.CharField(blank=True, max_length=40)),
                ('post_code', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=40)),
            ],
        ),
    ]
