# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_editorganisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditOrganisation',
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
    ]
