# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20200310_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='home_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
