# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200414_1707'),
        ('organisation', '0013_auto_20200319_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('subscription_count', models.SmallIntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.Organisation')),
                ('product_number', models.ForeignKey(db_column='product_number', on_delete=django.db.models.deletion.PROTECT, to='product.Product', to_field='number')),
            ],
            options={
                'ordering': ['organisation', 'product_number'],
            },
        ),
    ]
