# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='product_number',
            field=models.ForeignKey(db_column='product_number', on_delete=django.db.models.deletion.PROTECT, related_name='product_number', to='product.Product', to_field='number'),
        ),
    ]
