# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20200417_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
    ]
