# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_auto_20200420_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Enter name of your organisation or your full name if not an organisation.'),
        ),
    ]
