# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20200420_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='home_number',
            new_name='landline_number',
        ),
    ]
