# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-25 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_auto_20200420_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='address_4',
            new_name='town_and_city',
        ),
    ]
