# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0023_auto_20200426_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Enter name of your organisation or full name if not an organisation.'),
        ),
    ]
