# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20200510_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='updated_by',
        ),
    ]
