# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0026_remove_organisation_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
    ]
