# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_caption',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
