# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_unique_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_unique_product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_data_product',
            field=models.BooleanField(default=False, verbose_name='Is a data product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_subscription_product',
            field=models.BooleanField(default=False, verbose_name='Is a subscription product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_upgrade_product',
            field=models.BooleanField(default=False, verbose_name='Is an upgrade product?'),
        ),
    ]
