# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200414_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
