# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200414_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_single_use_only',
            field=models.BooleanField(default=False, verbose_name='Is a single use product?'),
        ),
    ]
