# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_users',
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_users',
            field=models.SmallIntegerField(default=0),
        ),
    ]
