# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200417_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_subscription_months',
            field=models.SmallIntegerField(default=0),
        ),
    ]
