# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200427_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number_of_users',
            new_name='number_of_devices',
        ),
    ]
