# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='post_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
