# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_street_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='street',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
