# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_auto_20200319_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.SmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Street')),
            ],
        ),
    ]
