# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='name',
        ),
    ]
