# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_auto_20200329_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='round.Street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='round.Round'),
        ),
    ]
