# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0006_auto_20200402_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name', 'door_number']},
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Street'),
        ),
    ]
