# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0007_auto_20200402_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='comments',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
