# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaign_round'),
        ('round', '0008_auto_20200402_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.Campaign'),
        ),
    ]
