# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0009_round_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='campaign',
            new_name='campaigns',
        ),
    ]
