# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0010_auto_20200512_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='campaigns',
        ),
    ]
