# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_remove_campaign_rounds'),
        ('round', '0011_remove_round_campaigns'),
    ]

    operations = [
    ]
