# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0012_auto_20200516_1936'),
    ]

    operations = [
    ]
