# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0015_auto_20200517_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
