# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0017_auto_20200529_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='round.Round'),
        ),
    ]
